/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeeklyReportRouteImport } from './routes/_authenticated.weekly-report'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedSentRouteImport } from './routes/_authenticated.sent'
import { Route as AuthenticatedRegisterRouteImport } from './routes/_authenticated.register'
import { Route as AuthenticatedProjectRouteImport } from './routes/_authenticated.project'
import { Route as AuthenticatedPmReviewRouteImport } from './routes/_authenticated.pm-review'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated.pending'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeeklyReportRoute =
  AuthenticatedWeeklyReportRouteImport.update({
    id: '/weekly-report',
    path: '/weekly-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSentRoute = AuthenticatedSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegisterRoute = AuthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectRoute = AuthenticatedProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPmReviewRoute = AuthenticatedPmReviewRouteImport.update({
  id: '/pm-review',
  path: '/pm-review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/pm-review': typeof AuthenticatedPmReviewRoute
  '/project': typeof AuthenticatedProjectRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/sent': typeof AuthenticatedSentRoute
  '/users': typeof AuthenticatedUsersRoute
  '/weekly-report': typeof AuthenticatedWeeklyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/pm-review': typeof AuthenticatedPmReviewRoute
  '/project': typeof AuthenticatedProjectRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/sent': typeof AuthenticatedSentRoute
  '/users': typeof AuthenticatedUsersRoute
  '/weekly-report': typeof AuthenticatedWeeklyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/pm-review': typeof AuthenticatedPmReviewRoute
  '/_authenticated/project': typeof AuthenticatedProjectRoute
  '/_authenticated/register': typeof AuthenticatedRegisterRoute
  '/_authenticated/sent': typeof AuthenticatedSentRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/weekly-report': typeof AuthenticatedWeeklyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/history'
    | '/pending'
    | '/pm-review'
    | '/project'
    | '/register'
    | '/sent'
    | '/users'
    | '/weekly-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/history'
    | '/pending'
    | '/pm-review'
    | '/project'
    | '/register'
    | '/sent'
    | '/users'
    | '/weekly-report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/pending'
    | '/_authenticated/pm-review'
    | '/_authenticated/project'
    | '/_authenticated/register'
    | '/_authenticated/sent'
    | '/_authenticated/users'
    | '/_authenticated/weekly-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weekly-report': {
      id: '/_authenticated/weekly-report'
      path: '/weekly-report'
      fullPath: '/weekly-report'
      preLoaderRoute: typeof AuthenticatedWeeklyReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sent': {
      id: '/_authenticated/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof AuthenticatedSentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/register': {
      id: '/_authenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedRegisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project': {
      id: '/_authenticated/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AuthenticatedProjectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pm-review': {
      id: '/_authenticated/pm-review'
      path: '/pm-review'
      fullPath: '/pm-review'
      preLoaderRoute: typeof AuthenticatedPmReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
  AuthenticatedPmReviewRoute: typeof AuthenticatedPmReviewRoute
  AuthenticatedProjectRoute: typeof AuthenticatedProjectRoute
  AuthenticatedRegisterRoute: typeof AuthenticatedRegisterRoute
  AuthenticatedSentRoute: typeof AuthenticatedSentRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWeeklyReportRoute: typeof AuthenticatedWeeklyReportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
  AuthenticatedPmReviewRoute: AuthenticatedPmReviewRoute,
  AuthenticatedProjectRoute: AuthenticatedProjectRoute,
  AuthenticatedRegisterRoute: AuthenticatedRegisterRoute,
  AuthenticatedSentRoute: AuthenticatedSentRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWeeklyReportRoute: AuthenticatedWeeklyReportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
